### ISSUE TITLE
New ClickGui, og liquidbounce gui can't scroll down and look messy.

### ISSUE THREAD

**Issue by hentlord** [WYSI-Foundation/LiquidBouncePlus#103]

**Comment by exit-scammed** [comment]
may take a while, 'been little sick and busy recently

**Comment by Tcm9** [comment]
You could make it so that you can scroll over. That's how I solved it.
![image](https://user-images.githubusercontent.com/31276706/166068312-412851ed-d625-44c9-be02-8aff87957184.png)
