### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by 1vrx** [WYSI-Foundation/LiquidBouncePlus#110]
Option for tags to just display the type and not the mode 
example: instead of "Speed NCP, Hop" it would be "Speed NCP" 

I tried changing myself but I am too retard. 

:) thanks in advanced if this is added 👍

**Comment by KnawKx** [comment]
this is the most useless change i've ever seen

**Comment by exit-scammed** [comment]
will add more way to customize speed tags.
