### ISSUE TITLE
AACHop4.3.8 (merging)

### ISSUE THREAD

**Issue by cheesethesylveon** [WYSI-Foundation/LiquidBouncePlus#111]
https://github.com/CCBlueX/LiquidBounce/commit/fc99e2c0a6a0e7b32f5d028d65a740f6bf2b1e61
currently in need of a Matrix speed, i am bad at doing customspeed

**Comment by Physuo** [comment]
custom speed sadly wont have enough controls for you to make a speed. you will need to make a script or code your own into the client

**Comment by exit-scammed** [comment]
merged.
