### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by FengXiaoSkidGod** [WYSI-Foundation/LiquidBouncePlus#115]
can you create a discord server?

=-=-=-=-=-=FDPFDPFDPFDPFDPFDPFDPFDPFDPFDP=-=-=-=-=-=-=--=-=-=-
=D-W==WFIAFDWAFD=GH=ET-J=E-=H-AD=HDAFHAHA

**Comment by opZywl** [comment]
https://discord.gg/GKAACYxWPd

**Comment by exit-scammed** [comment]
readme.
