### ISSUE TITLE
disabler

### ISSUE THREAD

**Issue by xuziangh** [WYSI-Foundation/LiquidBouncePlus#117]
blocksmc kill every use verus disabler's config,the sever ban  when you use the disabler move,

**Comment by xuziangh** [comment]
shit blocksmc

**Comment by exit-scammed** [comment]
flew around the map and won a game without ban.

**Comment by evghenii12** [comment]
![image](https://user-images.githubusercontent.com/55927996/164736449-bb93e4e3-b5bb-40be-94e6-e31a18e51d6a.png)

**Comment by evghenii12** [comment]
Try to use this settings.

**Comment by evghenii12** [comment]
![image](https://user-images.githubusercontent.com/55927996/164738779-2e61d2f7-ef27-4955-9658-1ed53a0edfda.png)

**Comment by xuziangh** [comment]
omg

**Comment by xuziangh** [comment]
but this disabler shouldn turn off debug dan verus-antifly

**Comment by xuziangh** [comment]
fly By all means use motion

**Comment by evghenii12** [comment]
Yea im know but motion works with kicks and clip fly working better.

**Comment by evghenii12** [comment]
Now we cant use motion fly

**Comment by xuziangh** [comment]
but,use this disabler i can motion fly,why?

**Comment by xuziangh** [comment]
emm

**Comment by xuziangh** [comment]
Are you konw,the day before yesterday，blocksmc want to Switch Anti-Cheating，it's,emm
AAc5+ncp+matrix

**Comment by xuziangh** [comment]
but now is verus too

**Comment by xuziangh** [comment]
blocksmc not swich Anti-Cheating
