### ISSUE TITLE
[Feature Request] Add another tpaura

### ISSUE THREAD

**Issue by evghenii12** [WYSI-Foundation/LiquidBouncePlus#120]
Add this infinite aura to liquidbounce+ https://raw.githubusercontent.com/commandblock2/LiquidBounce/reachaura/1.8.9-Forge/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/LegacyReachAura.kt

https://streamable.com/ddk50x

**Comment by exit-scammed** [comment]
commandblock2 has dropped support for this so i won't add, may find a way to make the current tpaura better
