### ISSUE TITLE
Tensioned bow is not displayed.

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#121]
When I tighten the bow, it is not displayed.
https://streamable.com/7szthn

**Comment by Tcm9** [comment]
![image](https://user-images.githubusercontent.com/31276706/166071894-0c58b87f-f5fb-4328-b1e0-11d7b05e8ced.png)
If I have the animation module on and Swing method on Swing or cancel, then the bow works again.
But I want the default swing animation. And with this it looks like this:
![image](https://user-images.githubusercontent.com/31276706/166072153-c48319ba-cf53-48d4-8afe-664b9e5d5dc6.png)
uff. I would prefer to just have the "animations" module off, but for the tense bow to still be displayed.

**Comment by Tcm9** [comment]
And even if I turn off the animation module, the swing method is still "Swing" and not default. But the stretched bow becomes invisible again.
![image](https://user-images.githubusercontent.com/31276706/166072565-3bc27c61-bf08-43e6-b031-9039acfabc45.png)

**Comment by Tcm9** [comment]
Info: I have reset the Liquidbounce+ settings and the normal settings. And the problem was still there. My OpenGl version is 4.6

**Comment by exit-scammed** [comment]
can confirm this does happen. i may need to rewrite animations module if possible.

**Comment by exit-scammed** [comment]
fixed.
