### ISSUE TITLE
Small improvements in the HUD module.

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#122]
- [x] If the sound of buttons in the HUD is turned on, this sound also sounds when you only open the Clickgui.
There would be an exception quite nice that there is no sound.

- [x] feature that the hotbar does not rise when the chat is called.
If you have certain mods in it, or a resource pack, then that can also look buggy or not good.

- [x] More Tab animations. e.g slide down or none.

- [x] Possibility to use the standard Minecraft or Liquidbounce buttons.
![image](https://user-images.githubusercontent.com/31276706/165544259-f915eaae-ff5b-4ae4-8f79-2a3e7a8b4412.png)

A clickgui module issue: 

- [x] Text of the modules in the middle
![image](https://user-images.githubusercontent.com/31276706/165548737-d27c0f33-b2d2-44ed-afbc-32b6a1664ee3.png)

**Comment by exit-scammed** [comment]
done.
