### ISSUE TITLE
More main menu designs.

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#123]
More designs as well as old ones like the LB or Minecraft design would be quite nice.

**Comment by Tcm9** [comment]
Animations: Container animation: 
- VSlide (from up/down), 
- HSlide (from left/right) and 
- Container animation speed setting.

**Comment by exit-scammed** [comment]
due to me merging all sub main menu guis into one the main menu designs will not be available, as i don't have much time left to release the final build.
