### ISSUE TITLE
Let's discuss something.plssssssss

### ISSUE THREAD

**Issue by VeibaeMCC** [WYSI-Foundation/LiquidBouncePlus#124]
Hello, I am a configuration producer. Because the FDP client stops supporting, I want to publish the configuration with your liquidbounceplus client. The configuration will be free. I will also use my configuration to help you promote this client. I hope to get your support. What's your opinion?

**Comment by xuziangh** [comment]
now blocksmc ban movedisabler,and he keep kick convert ban,Can you fix him

**Comment by xuziangh** [comment]
VeibaeMCC，can you give me your latest lb+ config bypass blocksmc.I want to get it

**Comment by xuziangh** [comment]
算了，用中文交流把

**Comment by Lafely** [comment]
https://discord.io/liquidbounceplus

**Comment by xuziangh** [comment]
bmc现在换反作弊了，是ncp

**Comment by contionability** [comment]
> Hello, I am a configuration producer. Because the FDP client stops supporting, I want to publish the configuration with your liquidbounceplus client. The configuration will be free. I will also use my configuration to help you promote this client. I hope to get your support. What's your opinion?

I'll keep update

**Comment by contionability** [comment]
but my last commit will be at 4/30 - 5/1
further updates/official websites will be pushed after my graduation from senior high school

**Comment by exit-scammed** [comment]
hm okay

**Comment by VeibaeMCC** [comment]
这。。。

**Comment by VeibaeMCC** [comment]
Co我看到你回复我的你的qq号了，但我的github被不知道哪个坏蛋在fdp的gitub被ban了，也许你可以给我unban

**Comment by VeibaeMCC** [comment]
> hm okay

thanks
