### ISSUE TITLE
BlocksMC had switched over vulcan.

### ISSUE THREAD

**Issue by codepatched** [WYSI-Foundation/LiquidBouncePlus#128]
I just got an report that BlocksMC has switched over to vulcan.
That means: No verus bypasses are working for BlocksMC.
If you are caught cheating on SkyWars ur instantly banned, might be auto ban.

**Comment by VeibaeMCC** [comment]
i have bypassed it by FDP ,10 hours ago , it is using Vulcan 2.7.01 build*#1002 version

**Comment by 7Sence** [comment]
Thank youuuuu
