### ISSUE TITLE
[request]

### ISSUE THREAD

**Issue by evghenii12** [WYSI-Foundation/LiquidBouncePlus#13]
Add animations from FDP Client

**Comment by exit-scammed** [comment]
Don't know what do you mean but we have lots of block animation for you to select (including GUI/container animations).

**Comment by evghenii12** [comment]
> Don't know what do you mean but we have lots of block animation for you to select (including GUI/container animations).
Im want to add ItemPosX ItemPosZ ItemPosY in animations

**Comment by exit-scammed** [comment]
okay.
