### ISSUE TITLE
TargetHud

### ISSUE THREAD

**Issue by xuziangh** [WYSI-Foundation/LiquidBouncePlus#130]
you can add this target hud to lb+https://forums.ccbluex.net/topic/3927/a-targethud-modeled-on-remix?_=1651235206512

**Comment by exit-scammed** [comment]
got you.
forum ver:
![8a981a1a-57bb-478c-a6e7-4e846195acf1](https://user-images.githubusercontent.com/85971344/166095612-d679b109-226f-4107-9bd7-fbe2e98f9536.png)
my ver:
![image](https://user-images.githubusercontent.com/85971344/166095619-4307b7bd-f3ad-4a9f-9b9a-cd2a03bc5573.png)
remix:
![image](https://user-images.githubusercontent.com/85971344/166095682-1de6924d-2e9f-4ff6-beb6-00c38ffc4b9d.png)

**Comment by exit-scammed** [comment]
will close this issue once its closest to the original.

**Comment by exit-scammed** [comment]
![image](https://user-images.githubusercontent.com/85971344/166096823-2ceb0c8a-be58-42b0-bbff-b2e4014e972c.png)
finished.
