### ISSUE TITLE
Creative Extra Items

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#131]
Liquidbounce itself already has this. Strangely, this is missing in the Plus version. For Timolia.de or other servers this can be very useful.
![image](https://user-images.githubusercontent.com/31276706/165986726-91349229-663a-42e1-a0df-64218d280aee.png)

Maybe you can add those extraitems from Liquidbounce again. Maybe even with additional items.
I'll name a few here if you want to add some extra Items:

-Trollstick with Knockback 127
-A nether portal block and an end portal block
-Water block and lava block
-Burning furnace (It burns but the stove is empty)
-Armor stand with arms

-more potions. e.g. Blindness or Nausea throwable potion or absorption, health boost potions.

-Weapons and Armor with Attributes
        (armor with extralifes "generic.maxHealth" e.g. 2 heart bars instead of one
         armor with antiknockback "generic.knockbackResistance"
         armor with more speed "generic.movementSpeed"
         weapons with more damage without enchantments "generic.attackDamage"

All just additional ideas. If you like something, you can add it. The important thing is that the creative menu itself has extra stuff.

```

Here. You can see a Chestplate with more lifes.
/give @p diamond_chestplate 1 0 {
    AttributeModifiers: [
        {
            AttributeName: "generic.maxHealth",
            Name: "generic.maxHealth",
            Amount: 20,
            Operation: 0,
            UUIDMost: 61963,
            UUIDLeast: 970786
        }
    ]
}
```

**Comment by exit-scammed** [comment]
done.
