### ISSUE TITLE
ClickGUI: Value change by mouseweel

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#133]
If I point in the ClickGUI to a Value or to a bar, then I should be able to change the number with the mouse wheel.
Mouse wheel up = value + 1
Mouse wheel down = value - 1
With some cheats like the Killaura range + 0,1 or - 0,1 should be changed with the mouse wheel.

With this you can always adjust everything exactly. Because this bar, where you can set the value, is usually quite inaccurate.

**Comment by exit-scammed** [comment]
great idea
