### ISSUE TITLE
Nameprotect lags / Own skin in skinprotect

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#136]
- [ ] first:
without nameprotect
![image](https://user-images.githubusercontent.com/31276706/166097329-4dbc8b2d-2e89-44fb-8ec0-1d0b9df7ee35.png)
with nameprotect
![image](https://user-images.githubusercontent.com/31276706/166097352-9fa88b0b-034d-4a3e-ba92-e5452d769913.png)

- [x] I would also find it good if you can give your own skin for the Skinprotect. If you play with alts, you can then have your main account skin. 
The skin should be saved in "...\Roaming.minecraft\LiquidBounce+-1.8\fakeskin.png".

**Comment by exit-scammed** [comment]
the first thing is really strange... can you send your latest.log here?

**Comment by Tcm9** [comment]
To the first: The problem is the Hud module. If Hud and NameProtect is switched on = lags.
and only, if the Arraylist is on.

**Comment by exit-scammed** [comment]
might have been fixed in the next update
