### ISSUE TITLE
new advises

### ISSUE THREAD

**Issue by mccboy520** [WYSI-Foundation/LiquidBouncePlus#14]
1.  let targetstrafe run all the time , or not only hypixel speed
2.  servercrasher ( type AAC5) is not working
3.  because I'm one of the owners of FDPclient , so i found you copied our client a lot (such as : China hat) . plz write out your skided action from FDPclient .
4.  you can add a new clickGUI like astolfo client

thanks for your listening!

**Comment by exit-scammed** [comment]
1. After looking into each speed modes I found Hypixel bypasses can work pretty well with TargetStrafe but not for the other. But if you want I can make it available for every mode soon.
2. yes and that's from your FDPClient.
3. Already done. (btw AsianHat aka. ChinaHat is **not** from FDPClient. I wrote it myself with custom colors.)
4. Probably in a near future.

**Comment by mccboy520** [comment]
although this , I'm sorry to know Asianhat is made by yourself . but they r really similar . i think astolfo's click gui isn't so beautiful , so if you are great enough , you can add new flux-client click gui .

i know that you are tired , so you don't need to update so quickly , but you shouldn't update once a month , that's too slowly .

if you can , i adviced you to copy our client's targetstrafe (it has been removed from it , but it is still in our source code) , it can work all the time (after opening killaura , but not must use speed) .

thanks for listening.

**Comment by mccboy520** [comment]
i know Asianhat is made yourself , but your this idea must be from us . ( kidding)

**Comment by mccboy520** [comment]
our servercrasher can work well , May be you made some mistakes .

**Comment by exit-scammed** [comment]
> i know Asianhat is made yourself , but your this idea must be from us . ( kidding)

tbh I have no idea, just see rise have one so I decided to recreate their hat.

> our servercrasher can work well , May be you made some mistakes .

hmm okay will probably fix soon

> although this , I'm sorry to know Asianhat is made by yourself . but they r really similar . i think astolfo's click gui isn't so beautiful , so if you are great enough , you can add new flux-client click gui .
> 
> i know that you are tired , so you don't need to update so quickly , but you shouldn't update once a month , that's too slowly .
> 
> if you can , i adviced you to copy our client's targetstrafe (it has been removed from it , but it is still in our source code) , it can work all the time (after opening killaura , but not must use speed) .
> 
> thanks for listening.

will add a different TargetStrafe from your old FDP source code but fixed to be compatible with every speed mode.
and about the update frequency, I will try my best to update faster but my goal now is to create a new ClickGUI, so that may take sometime.

**Comment by mccboy520** [comment]
yeah , your client's viavertion needs a updating , Minecraft 1.17.1 can be supported now .

**Comment by exit-scammed** [comment]
> yeah , your client's viavertion needs a updating , Minecraft 1.17.1 can be supported now .

okay, will try to merge with the latest ViaForge update.

**Comment by opZywl** [comment]
> embora isso, lamento saber que Asianhat é feito por você. mas eles são muito parecidos. Eu acho que o click gui de Astolfo não é tão bonito, então se você for bom o suficiente, você pode adicionar um novo flux-client click gui.
> 
> Eu sei que você está cansado, então você não precisa atualizar tão rápido, mas você não deve atualizar uma vez por mês, isso é muito lento.
> 
> se puder, aconselho a copiar o targetstrafe de nosso cliente (foi removido dele, mas ainda está em nosso código-fonte), ele pode funcionar o tempo todo (depois de abrir o killaura, mas não deve usar a velocidade).
> 
> obrigado por ouvir.

ast

> although this , I'm sorry to know Asianhat is made by yourself . but they r really similar . i think astolfo's click gui isn't so beautiful , so if you are great enough , you can add new flux-client click gui .
> 
> i know that you are tired , so you don't need to update so quickly , but you shouldn't update once a month , that's too slowly .
> 
> if you can , i adviced you to copy our client's targetstrafe (it has been removed from it , but it is still in our source code) , it can work all the time (after opening killaura , but not must use speed) .
> 
> t
![unknown (6)](https://user-images.githubusercontent.com/86253343/134952177-a02b68c4-7fdb-420f-bbb5-85860dfe2bf0.png)
hanks for listening.

lol astolfo clickgui is good

**Comment by opZywl** [comment]
I started once but I didn't finish because I'm pretty lazy asasashasa

**Comment by opZywl** [comment]
> 1. let targetstrafe run all the time , or not only hypixel speed
> 2. servercrasher ( type AAC5) is not working
> 3. because I'm one of the owners of FDPclient , so i found you copied our client a lot (such as : China hat) . plz write out your skided action from FDPclient .
> 4. you can add a new clickGUI like astolfo client
> 
> thanks for your listening!

no problem we copied a lot of it, we allowed him to copy it he brought us a lot of stuff and his client is really nice
I myself added so many things to fdpclient that comes straight from this custom build, it really is very good!
he is talented fdpclient is great if he would help us contribute there it would be really cool because i like the looks of this client are much better than fdp and i see potential

**Comment by opZywl** [comment]
I made a mistake in adding things without asking him, I'm sure he was furious well anyone would be but we don't need to start a war I like his custom build and it would even help spread the word:) I don't want fdpclient to be in a fight with him! he was very helpful and cool

**Comment by mccboy520** [comment]
@opZywl you u right , i think so too . our fdpclient isn't better than your liquidbounceplus in something . you all are great . everyone don't want a war . although i am owner of fdpclient , but i find better something created in your client , try your best to do better .

**Comment by mccboy520** [comment]
come on

**Comment by mccboy520** [comment]
you used to update sourcecode to us . so i think your idea is good still , if you have good idea , you can tell me in fdpclient's github . we have many programmers (not only me) , so we will try our best to achieve it .

**Comment by RangelMK** [comment]
> come on

bro Zywl is one of the developers fdpclient too -' you must have never entered the fdpclient discord and I never saw you as a developer either
he's always been online on discord apparently for a long time too and Zywl has sent a lot of stuff to fdpclient he's not a LiquidBounce+ developer, he's just a FDPClient developer

FDP Developers:
LiuliHaoCai 
Zywl 
Contionability
XingXong
Sussy

**Comment by RangelMK** [comment]
> > embora isso, lamento saber que Asianhat é feito por você. mas eles são muito parecidos. Eu acho que o click gui de Astolfo não é tão bonito, então se você for bom o suficiente, você pode adicionar um novo flux-client click gui.
> > Eu sei que você está cansado, então você não precisa atualizar tão rápido, mas você não deve atualizar uma vez por mês, isso é muito lento.
> > se puder, aconselho a copiar o targetstrafe de nosso cliente (foi removido dele, mas ainda está em nosso código-fonte), ele pode funcionar o tempo todo (depois de abrir o killaura, mas não deve usar a velocidade).
> > obrigado por ouvir.
> 
> ast
> 
> > although this , I'm sorry to know Asianhat is made by yourself . but they r really similar . i think astolfo's click gui isn't so beautiful , so if you are great enough , you can add new flux-client click gui .
> > i know that you are tired , so you don't need to update so quickly , but you shouldn't update once a month , that's too slowly .
> > if you can , i adviced you to copy our client's targetstrafe (it has been removed from it , but it is still in our source code) , it can work all the time (after opening killaura , but not must use speed) .
> > t
> > ![unknown (6)](https://user-images.githubusercontent.com/86253343/134952177-a02b68c4-7fdb-420f-bbb5-85860dfe2bf0.png)
> > hanks for listening.
> 
> lol astolfo clickgui is good

add clickgui from fdpclient and liquidbounce+ please

**Comment by opZywl** [comment]
> you used to update sourcecode to us . so i think your idea is good still , if you have good idea , you can tell me in fdpclient's github . we have many programmers (not only me) , so we will try our best to achieve it .

My idea is to make fdpclient always the best I always send things after all to a list of things I sent to be added assuashas

**Comment by opZywl** [comment]
> > come on
> 
> bro Zywl is one of the developers fdpclient too -' you must have never entered the fdpclient discord and I never saw you as a developer either
> he's always been online on discord apparently for a long time too and Zywl has sent a lot of stuff to fdpclient he's not a LiquidBounce+ developer, he's just a FDPClient developer
> 
> FDP Developers:
> LiuliHaoCai
> Zywl
> Contionability
> XingXong
> Sussy

yes, i contribute to fdpclient since its first versions, but i dont have qq so i am not in the group but on fdpclient discord we can say i am active every day

**Comment by opZywl** [comment]
> > > embora isso, lamento saber que Asianhat é feito por você. mas eles são muito parecidos. Eu acho que o click gui de Astolfo não é tão bonito, então se você for bom o suficiente, você pode adicionar um novo flux-client click gui.
> > > Eu sei que você está cansado, então você não precisa atualizar tão rápido, mas você não deve atualizar uma vez por mês, isso é muito lento.
> > > se puder, aconselho a copiar o targetstrafe de nosso cliente (foi removido dele, mas ainda está em nosso código-fonte), ele pode funcionar o tempo todo (depois de abrir o killaura, mas não deve usar a velocidade).
> > > obrigado por ouvir.
> > 
> > 
> > ast
> > > although this , I'm sorry to know Asianhat is made by yourself . but they r really similar . i think astolfo's click gui isn't so beautiful , so if you are great enough , you can add new flux-client click gui .
> > > i know that you are tired , so you don't need to update so quickly , but you shouldn't update once a month , that's too slowly .
> > > if you can , i adviced you to copy our client's targetstrafe (it has been removed from it , but it is still in our source code) , it can work all the time (after opening killaura , but not must use speed) .
> > > t
> > > ![unknown (6)](https://user-images.githubusercontent.com/86253343/134952177-a02b68c4-7fdb-420f-bbb5-85860dfe2bf0.png)
> > > hanks for listening.
> > 
> > 
> > lol astolfo clickgui is good
> 
> add clickgui from fdpclient and liquidbounce+ please

I will try to tell liulihaocai, maybe he will add it, but I don't think so because the new clickgui has already been released recently

**Comment by mccboy520** [comment]
@RangelMK because of VPN , i use discord not easy . so i active in our QQ team , what questions do you have .

**Comment by mccboy520** [comment]
总之琉璃酱是我的就对了
