### ISSUE TITLE
Main Screen Glitch at Self build

### ISSUE THREAD

**Issue by rezaebi** [WYSI-Foundation/LiquidBouncePlus#145]
![image](https://user-images.githubusercontent.com/90617105/166430122-9ab068ad-ce95-42f9-8f6b-fb2226651d1b.png)
bug in screen

**Comment by exit-scammed** [comment]
check for any text named `liquidbounce+` and replace it with your client_name may help.

**Comment by rezaebi** [comment]
@exit-scammed what about background ? its random colored

**Comment by exit-scammed** [comment]
please note that changing the `CLIENT_NAME` variable may severely break the client.
