### ISSUE TITLE
KIllaura

### ISSUE THREAD

**Issue by xuziangh** [WYSI-Foundation/LiquidBouncePlus#146]
now plus's killaura can't turn your head,can't bypass many sever now,Please fix it

**Comment by Nerbles1** [comment]
Turn your rotation speed up

**Comment by xuziangh** [comment]
pls send potos ,pls

**Comment by xuziangh** [comment]
what
<img width="92" alt="image" src="https://user-images.githubusercontent.com/103920679/166911705-56c17e71-4521-4ed6-a6d7-992eb8bbb702.png">

**Comment by Nerbles1** [comment]
Hmm, its probably rotating too fast and flagging the anticheat i always use 150 max 120min and if you want to see rotations in f3 toggle the rotations module

**Comment by xuziangh** [comment]
It's not working

**Comment by Nerbles1** [comment]
That's odd i dont see anything wrong, it might be a bug but im not sure though

**Comment by xuziangh** [comment]
can you give me you config?

**Comment by xuziangh** [comment]
bypass blocksmc?

**Comment by Nerbles1** [comment]
I cant right now
