### ISSUE TITLE
是的，Veibae姐姐在中国将延续这个客户端的精神继续开发。

### ISSUE THREAD

**Issue by VeibaeMCC** [WYSI-Foundation/LiquidBouncePlus#153]
我会把这个客户端重命名Veibae Client继续开发，没开玩笑哦！就在今年暑假我中考回来

2022年Veibae Client暑假公测发布位置：https://github.com/VeibaeMCC/VeibaeConfigs

**Comment by VeibaeMCC** [comment]
Bro **exit-scammed** U R a nice coder!

**Comment by contionability** [comment]
好家伙

**Comment by VeibaeMCC** [comment]
我其实是深藏不漏的软件工程师

**Comment by VeibaeMCC** [comment]
@contionability

**Comment by VeibaeMCC** [comment]
我曾经参与过win10的服务项开发，还有微软纪念邮箱捏

**Comment by VeibaeMCC** [comment]
如果6月20我中考完回来休息几天就开始的话，七月中旬就能公测！

**Comment by VeibaeMCC** [comment]
相信姐姐能做到捏 :thumbsup::thumbsup::thumbsup:

**Comment by contionability** [comment]
《初中生》
离谱

**Comment by contionability** [comment]
总之FDPClient被西瓜搞烂了
就很烦

**Comment by xuziangh** [comment]
那个

**Comment by xuziangh** [comment]
接手的话，我很支持

**Comment by xuziangh** [comment]
但，能不能不要吧名字改成Veibae Client，听着不习惯

**Comment by xuziangh** [comment]
还是叫liquidbounceplus吧

**Comment by xuziangh** [comment]
毕竟lb+已经1年多了

**Comment by contionability** [comment]
人家是延续

原客户端已经停更了
没必要续命

**Comment by xuziangh** [comment]
可是，原作者说，还有一个版本

**Comment by VeibaeMCC** [comment]
那原作者在哪里说过捏？

**Comment by VeibaeMCC** [comment]
我这个客户端将会很安全，几乎没有被破解的可能，毕竟有微软servers的安全引导基础

**Comment by VeibaeMCC** [comment]
希望我能成功吧，就算给所有喜欢我的人一个好的交代，高中之后我就几乎没时间开发了，只能维护一个暑假，希望我高中这三年有人替我更新@contionability 对吧？qwq

**Comment by VeibaeMCC** [comment]
高考回来继续肝，大学四年使劲肝

**Comment by SkiderKiller** [comment]
对于国人开源素质，我深表堪忧。

**Comment by SkiderKiller** [comment]
LiquidBouncePlus基于LiquidBounce进行二次开发，并遵守GPLv3进行开源，但在你的库中明确表示了不会开源，我不认为这是一种精神的延续。
CCbluex目前只授权过Aquavit对LiquidSense进行混淆。
在胸有大志时，应当遵守最基本的开源协议，再谈开源精神。

**Comment by RareCO** [comment]
Lol What the fuck is this guy

**Comment by SinoAHpx** [comment]
有趣的事实: https://github.com/WYSI-Foundation/LiquidBouncePlus/blob/no-wdl/LICENSE
英雄联盟

**Comment by VeibaeMCC** [comment]
> LiquidBouncePlus基于LiquidBounce进行二次开发，并遵守GPLv3进行开源，但在你的库中明确表示了不会开源，我不认为这是一种精神的延续。 CCbluex目前只授权过Aquavit对LiquidSense进行混淆。 在胸有大志时，应当遵守最基本的开源协议，再谈开源精神。

我不希望下一个***被小学生圈钱利用的端***出现，gitee的更新已经让我很失望了，我已经彻底不指望国内的开源素质有多高了

**Comment by VeibaeMCC** [comment]
> LiquidBouncePlus基于LiquidBounce进行二次开发，并遵守GPLv3进行开源，但在你的库中明确表示了不会开源，我不认为这是一种精神的延续。 CCbluex目前只授权过Aquavit对LiquidSense进行混淆。 在胸有大志时，应当遵守最基本的开源协议，再谈开源精神。

我在b站明确表示不会使用lb的基础源码，所以不遵循当前开源协议

**Comment by VeibaeMCC** [comment]
> LiquidBouncePlus基于LiquidBounce进行二次开发，并遵守GPLv3进行开源，但在你的库中明确表示了不会开源，我不认为这是一种精神的延续。 CCbluex目前只授权过Aquavit对LiquidSense进行混淆。 在胸有大志时，应当遵守最基本的开源协议，再谈开源精神。

也许fdp就是最好的也最遗憾的例子

**Comment by SkiderKiller** [comment]
> > LiquidBouncePlus基于LiquidBounce进行二次开发，并遵守GPLv3进行开源，但在你的库中明确表示了不会开源，我不认为这是一种精神的延续。 CCbluex目前只授权过Aquavit对LiquidSense进行混淆。 在胸有大志时，应当遵守最基本的开源协议，再谈开源精神。
> 
> 我不希望下一个_**被小学生圈钱利用的端**_出现，gitee的更新已经让我很失望了，我已经彻底不指望国内的开源素质有多高了

很有趣的是 你就是破坏协议的一份子。

**Comment by SkiderKiller** [comment]
> > LiquidBouncePlus基于LiquidBounce进行二次开发，并遵守GPLv3进行开源，但在你的库中明确表示了不会开源，我不认为这是一种精神的延续。 CCbluex目前只授权过Aquavit对LiquidSense进行混淆。 在胸有大志时，应当遵守最基本的开源协议，再谈开源精神。
> 
> 也许fdp就是最好的也最遗憾的例子

FDP并不遗憾。

**Comment by veibaeCCM** [comment]
@VeibaeMCC “坦克人”是一名身份不详的男性示威者，于1989年6月5日（即[六四天安门事件](https://zh.wikipedia.org/wiki/%E5%85%AD%E5%9B%9B%E5%A4%A9%E5%AE%89%E9%97%A8%E4%BA%8B%E4%BB%B6)的翌日）在[北京](https://zh.wikipedia.org/wiki/%E5%8C%97%E4%BA%AC)[长安街](https://zh.wikipedia.org/wiki/%E9%95%B7%E5%AE%89%E8%A1%97)上只身阻挡[中国人民解放军](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E4%BA%BA%E6%B0%91%E8%A7%A3%E6%94%BE%E5%86%9B)坦克车队前进[[3]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-3)。其照片成为近代历史上最为著名的照片之一[[4]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-Patrick_Witty_1-4)。该名示威者尝试阻挡约18辆[59式坦克](https://zh.wikipedia.org/wiki/59%E5%BC%8F%E5%9D%A6%E5%85%8B)车队行进。尽管领头的坦克驾驶一度试图转向绕过，但是仍然遭到拦阻而不得前进。该名示威者其后还爬上坦克[炮塔](https://zh.wikipedia.org/wiki/%E7%A0%B2%E5%A1%94)，并试图和车长沟通。他似乎被说服而离开，坦克队伍则继续往前行进，但由于该名示威者又跑向前，驾驶员再度紧急煞停，对话一阵子后，在僵持之际，一名骑单车的男子前来劝说，最终他被几名身穿蓝色制服人士带离现场。示威者独自阻挡坦克队伍行进的过程，被[杰夫·怀德纳](https://zh.wikipedia.org/wiki/%E6%9D%B0%E5%A4%AB%C2%B7%E6%80%80%E5%BE%B7%E7%BA%B3)等摄影师及国外媒体记录下来。很快地，相关照片和影像随即在国际间各大报纸头版与新闻媒体中广为流传和引起讨论[[4]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-Patrick_Witty_1-4)。

许多关于[六四天安门事件](https://zh.wikipedia.org/wiki/%E5%85%AD%E5%9B%9B%E5%A4%A9%E5%AE%89%E9%97%A8%E4%BA%8B%E4%BB%B6)的纪录片和相关展览上，都会提及示威者阻挡坦克这一事件[[5]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-%E8%BE%9B%E8%8F%B2-5)，并将“坦克人”视为六四的标志性象征[[6]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-6)。外界一直流传该示威者姓名为“王维林”，该名最早是以英文拼音“Wang Weilin”出现在[英国](https://zh.wikipedia.org/wiki/%E8%8B%B1%E5%9C%8B)《[星期日快报](https://zh.wikipedia.org/wiki/%E6%AF%8F%E6%97%A5%E5%BF%AB%E5%A0%B1)》上[[7]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-%E6%B4%9B%E6%9D%89%E7%A3%AF%E6%99%82%E5%A0%B1-7)，但该示威者的确切身份及下落至今依然不明[[8]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-%E7%9A%AE%E7%A7%91%C2%B7%E8%89%BE%E7%88%BE-8)，而不同新闻媒体对于该示威者者更有不同称呼。[公共电视网](https://zh.wikipedia.org/wiki/%E5%85%AC%E5%85%B1%E5%B9%BF%E6%92%AD%E7%94%B5%E8%A7%86%E5%85%AC%E5%8F%B8)节目《[前线](https://zh.wikipedia.org/wiki/%E5%89%8D%E7%BA%BF_(%E7%BE%8E%E5%9B%BD%E7%94%B5%E8%A7%86%E8%8A%82%E7%9B%AE))》曾在2006年为此拍摄纪录片[[4]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-Patrick_Witty_1-4)。
![tankman](https://user-images.githubusercontent.com/108385528/176354609-b08d353e-e8cf-4482-8331-676551cc107a.jpeg)
[八一电影制片厂](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%9B%BD%E4%BA%BA%E6%B0%91%E8%A7%A3%E6%94%BE%E5%86%9B%E6%96%87%E5%8C%96%E8%89%BA%E6%9C%AF%E4%B8%AD%E5%BF%83%E7%94%B5%E5%BD%B1%E7%94%B5%E8%A7%86%E5%88%B6%E4%BD%9C%E9%83%A8)出品的新闻纪录片《[飘扬，共和国的旗帜](https://zh.wikipedia.org/wiki/%E9%A3%98%E6%89%AC%EF%BC%8C%E5%85%B1%E5%92%8C%E5%9B%BD%E7%9A%84%E6%97%97%E5%B8%9C)》将该名男子称为“螳臂挡车的歹徒”[[9]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-%E5%85%AB%E4%B9%9D%E5%A4%A9%E5%AE%89%E9%96%80%E4%BA%8B%E4%BB%B6%E8%A7%A3%E6%94%BE%E8%BB%8D%E7%B8%82%E6%94%BF%E6%B2%BB%E9%83%A8%E8%B3%87%E6%96%99%E7%89%87-9)。西方社会则将该名男子称作“坦克人”（Tank Man），或者是“无名的抗议者”（Unknown Protester）。1998年4月，美国《[时代](https://zh.wikipedia.org/wiki/%E6%99%82%E4%BB%A3_(%E9%9B%9C%E8%AA%8C))》杂志将该名男子以“无名的反抗者”（The Unknown Rebel）为名，评选为20世纪最具影响力的[100个人物](https://zh.wikipedia.org/wiki/%E6%97%B6%E4%BB%A3100%E4%BA%BA%EF%BC%9A%E6%9C%AC%E4%B8%96%E7%BA%AA%E6%9C%80%E9%87%8D%E8%A6%81%E7%9A%84%E4%BA%BA%E7%89%A9)之一。而在2003年时，由《[生活](https://zh.wikipedia.org/wiki/%E7%94%9F%E6%B4%BB_(%E9%9B%9C%E8%AA%8C))》杂志发行的《[改变世界的100幅照片](https://zh.wikipedia.org/w/index.php?title=%E6%94%B9%E8%AE%8A%E4%B8%96%E7%95%8C%E7%9A%84100%E5%B9%85%E7%85%A7%E7%89%87&action=edit&redlink=1)》中，同样也收录了阻挡坦克车队的照片，尽管相关影像纪录被视为20世纪标志性的象征，但由于中国政府禁止[互联网](https://zh.wikipedia.org/wiki/%E7%B6%B2%E

https://user-images.githubusercontent.com/108385528/176354583-b85da338-c8fe-4e63-8e8c-f310ab5849a4.mp4

9%9A%9B%E7%B6%B2%E8%B7%AF)上流传相关图像，导致大部分中国民众对此并不了解[[4]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-Patrick_Witty_1-4)。2019年9月，照片的其中一名摄影师[查理·柯尔](https://zh.wikipedia.org/wiki/%E6%9F%A5%E7%90%86%C2%B7%E6%9F%AF%E7%88%BE_(%E6%94%9D%E5%BD%B1%E5%B8%AB))在[印尼](https://zh.wikipedia.org/wiki/%E5%8D%B0%E5%B0%BC)[峇厘岛](https://zh.wikipedia.org/wiki/%E5%B3%87%E9%87%8C%E5%B3%B6)逝世[[10]](https://zh.wikipedia.org/zh-sg/%E5%9D%A6%E5%85%8B%E4%BA%BA#cite_note-10)。
