### ISSUE TITLE
Safe Minecraft Settings, Restore Launcher Account and Hide Clickgui Module

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#155]
- [ ] Safe Minecraft Settings
When I go from 1.8 to Minecraft version 1.12 or 1.15 and then back to 1.8, many settings are reset. Can Liquidbounce+ access its own safefile or can the old one be swapped with the one in the lb+ folder on startup and swapped back on close? 
(options.txt, optionsof.txt and optionsshaders.txt)

- [x] Altmanager: Launcher Account Button
Meanwhile there are Microsoft accounts. And if I go into an Alt account, I can't just go back into my Main account. It would be nice if there is a button in the Altmanager where I can go back into my Launcher account.

- [ ]  Hidemodule
If I don't play on some servers like Hypixel, then I don't need some modules like Banchecker, autoplay or Autologin. It would be nice if you can hide modules from the clickgui with ".hidemodule hide <module>". There is already .hide but you can only hide the modules in the HUD and not the ClickGUI.

**Comment by exit-scammed** [comment]
like backing up current minecraft settings (optifine, etc.) on close and then load it on startup?

**Comment by Tcm9** [comment]
yes
