### ISSUE TITLE
why does multimc crash everytime i use LiquidBouncePlus?

### ISSUE THREAD

**Issue by Astralrr** [WYSI-Foundation/LiquidBouncePlus#156]
so i use multimc, and everytime i try to use liquidbounceplus with multimc it crashes and gives a process exit code of -1. but with the normal liquidbounce it works

**Comment by Tcm9** [comment]
did you cheack the antiforge settings?

**Comment by Tcm9** [comment]
or the Patches/Performance module?

**Comment by Astralrr** [comment]
> did you cheack the antiforge settings?

uh wdym? i literally cant launch the game this is my first time downloading and launching and it doesn't work

**Comment by exit-scammed** [comment]
Please provide more information, including:
- Your mods folder (`.minecraft/mods`)
- Log file (latest.log and fml-client-latest.log if you have, in `.minecraft/logs`)
In your case with MultiMC, the folder should be inside `instances/1.8.9/`

**Comment by Astralrr** [comment]
> Please provide more information, including:
> 
> * Your mods folder (`.minecraft/mods`)
> * Log file (latest.log and fml-client-latest.log if you have, in `.minecraft/logs`)
> 
> In your case with MultiMC, the folder should be inside `instances/1.8.9/`

Here's my mods
![image](https://user-images.githubusercontent.com/100779093/168511966-67a98b28-f5b2-41a9-b61b-4213e45cb933.png)
and the logs!
[fml-client-latest.log](https://github.com/WYSI-Foundation/LiquidBouncePlus/files/8696862/fml-client-latest.log)
[2022-04-25-1.log.gz](https://github.com/WYSI-Foundation/LiquidBouncePlus/files/8696863/2022-04-25-1.log.gz)
Note! ive used the normal liquidbounce client and it works with all of the mods! but for some reason using LiquidbouncePlus with the same mods keeps crashing

**Comment by exit-scammed** [comment]
the problem might have been caused by liquidbounceplus' built in patcher features. i may remove them in the next build, along with proper fixes.

**Comment by Astralrr** [comment]
> the problem might have been caused by liquidbounceplus' built in patcher features. i may remove them in the next build, along with proper fixes.

i tried removing patcher! but that also didn't work, also heres the minecraft log that i forgot to add in my last reply https://paste.ee/p/Goibo

**Comment by Astralrr** [comment]
> > the problem might have been caused by liquidbounceplus' built in patcher features. i may remove them in the next build, along with proper fixes.
> 
> i tried removing patcher! but that also didn't work, also heres the minecraft log that i forgot to add in my last reply https://paste.ee/p/Goibo

EDIT! I Found the issue why it kept on crashing, it was something caused by essential, which for some reason was in my keystrokes mod i just removed that and it works now!
