### ISSUE TITLE
Bypass MineLand cheat files check plz

### ISSUE THREAD

**Issue by ffffffffawd** [WYSI-Foundation/LiquidBouncePlus#157]

**Comment by exit-scammed** [comment]
proof that it detects your files.

**Comment by Ali00035v2** [comment]
> proof that it detects your files.

it does

**Comment by contionability** [comment]
I think Mineland doesn't have that check
because it's based on 1.16 with ViaBackwards

**Comment by ffffffffawd** [comment]
but they have recource check file
i can bypass them ,just need change file name to bypass(huh)

**Comment by ffffffffawd** [comment]
@contionability I think u need try to join mineland with LiquidBounce or Flux
