### ISSUE TITLE
Cool modules and ideas that can make lb+ even better.

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#159]
I still have a few ideas for the last update. Feel free to look at them and add the ones you like. I will also write here again reasons for the bypass.

- [ ] Xray seed mode
The client looks for the seed of the world and loads exactly this seed when xray is activated. AntiXray bypass. However, changes of the world are not displayed while xray is on. But this is not important. You can find out the seed e.g via a seedcracker(https://github.com/19MisterX98/SeedcrackerX).

- [ ] Xray cavefinder mode
![image](https://user-images.githubusercontent.com/31276706/169791339-c3d953ac-efae-4d60-8195-990d1aabc02f.png)

- [ ] AutoTool setting:
no Sword: When a sword is held, Autotool is inactive.
no Pvp: When killaura is enabled, Autotool is inactive.
(switchback: After block break, Autotool jumps back to the actual slot.) -> can also simply be in silent mode.
silent: No tools are switched in the client.

- [ ] Killaura rotarion: Overaim 
(This is just an idea, since the rotation method deviates from the standard and could therefore bypass.)
(Somewhat exaggerated in the picture.)
![image](https://user-images.githubusercontent.com/31276706/169792392-39f949a6-2e5a-429c-8ac2-dfcad08d694d.png)

- [ ]  Killaura: RandomCenter and Outboarder: Custom Y
Outboarder always hits top right and Randomcenter always hits bottom. Both cannot be switched on like this. A custom Y, where the player is hit if possible (prefer: head, chest, legs, boots) can help.

- [ ] Killaura: PreAim
Killaura slowly aims at the player before he hits.
Setting: PreRange = 0.5 (Killaura looks at a range of 0.5+range already on the player without hitting him.) 
PreTurnspeed = 20 (Killaura turns with the turnspeed already on the player without hitting him).

- [ ] .invsee Command + better MiddleClick module
If you enter .invsee playername, a large container will open. In this container the player's armor and the item he is currently holding are displayed. If he changes his hand items then these items will be added to the container. 
(In there you can see the enchantments, durability and other items of others.)
addition:
MCF -> MiddleClick
Settings: 
-Add Friend (The old MCF)
-RemoteView (You can see the view of the player) (dot command is in lb but not in lb+)
-InvSee (You can see parts of his inventory)
(If RemoteView or InvSee is selected, then the range for the target should be infinite.)

- [x] No slow: sneak
You can adjust the speed of the sneak. (Sneak forward/ Sneak strafe)

- [ ] Looking for intave bypasses (e.g Scaffold, Velocity and Speed)
Liquidbounce plus has hardly any bypasses for this anticheat. Maybe you can find some bypasses for this Anticheat.
On the server "gommehd.net" you can find the anticheat. (it is one of the biggest german Minecraft servers)

- [ ] Projectiles: allplayers
For other players, an arrow line will also be visible so that you can see where other players are shooting.

- [x] Tracer fov and directline setting
Fov: Shows only in a certain radius the targets.
![image](https://user-images.githubusercontent.com/31276706/169795656-9b926590-3237-457e-935a-98ac5106ee00.png)
Directline: The tracer knit does not go to the legs, and then to the head. The Tracer line should go directly to the upper body. 
![image](https://user-images.githubusercontent.com/31276706/178108412-48594100-b6f4-4692-9a1d-6112d57aaca3.png)

- [ ] InSight
It will be shown to you when a player sees you in firstperson. If you want to cheat unnoticed, this module can help you not to get caught. If you see that you are not seen, you can briefly activate scaffold or fly.
(The module may become difficult. Creating the degree can still be easy, but that looking through walls does not count would have to be implemented. Alternatively, you can do without the block check or improvise.)
Setting: Fov (Here you can simulate the fov of the opponent.)

- [ ] Altmanager: Mark if account not work + add "change Altfile" button (If you want use a other LB Altfile)
If an account is no longer working, it will be displayed as invalid.
![image](https://user-images.githubusercontent.com/31276706/169796216-2ae93eaa-fade-4fc2-9edc-3ec7797e4b3a.png)

- [ ] Autoarmor: illusion
The armor is taken off by default. Only when a player approaches, Autoarmor quickly puts on the armor.
If you have good armor, then many run away from you. But if you act like you don't have armor, then everyone wants to fight you. And suddenly you do have good armor.
setting: EquipRange = e.g 8

- [ ] Clickgui setting: add localautosettings list
![image](https://user-images.githubusercontent.com/31276706/169796779-4cb0d71e-f0fa-41f0-b619-6bde5499de74.png)

- [x] Noswing: Noblockbreak
No cracks are displayed during breaking (Serverside and Clientside)

- [ ] Commandblocksight
You can also look into the command block in survival mode.

**Comment by contionability** [comment]
Killaura: only hit if rotation valid already exists

**Comment by exit-scammed** [comment]
the issue with HurtTime value in KillAura settings is actually LiquidBounce feature, which sorts and filters out targets with hurtTime lower than desired value.

**Comment by Tcm9** [comment]
Ok, I have replaced that. Thought there was something strange. But if it is normal, then everything fits.
