### ISSUE TITLE
Clickgui's mouse wheel fails in Android PojavLauncher 

### ISSUE THREAD

**Issue by TalentsDX** [WYSI-Foundation/LiquidBouncePlus#171]
I found on PojavLauncher that LiquidBounce + works perfectly, but the mouse scrolling for the clickgui fails. Other than that, the other modules work perfectly

**Comment by exit-scammed** [comment]
can you provide me with a recording of the problem? also do you stimulate the scroll wheel or actually use a connected physical mouse?

**Comment by TalentsDX** [comment]
> can you provide me with a recording of the problem? also do you stimulate the scroll wheel or actually use a connected physical mouse?

It is not a physical mouse scroll, it is mapped

**Comment by exit-scammed** [comment]
do you have a screen recording that represents the scrolling problem? I may need that for the diagnostic

**Comment by TalentsDX** [comment]
https://user-images.githubusercontent.com/87688330/177311773-936d17bd-02bf-48fa-affd-c6346999cce4.mp4

**Comment by exit-scammed** [comment]
can you check whether this one https://github.com/WYSI-Foundation/LiquidBouncePlus/actions/runs/2615725410
or this one works for you https://github.com/WYSI-Foundation/LiquidBouncePlus/actions/runs/2615744055
reply back to me asap

**Comment by TalentsDX** [comment]
Same result

**Comment by TalentsDX** [comment]
https://user-images.githubusercontent.com/87688330/177318909-3ec778c3-8e98-4237-824c-c524dfc9ef2e.mp4

**Comment by TalentsDX** [comment]
This is the first option, and the second option is not responding

**Comment by TalentsDX** [comment]
It works perfectly. Thanks to the developer

**Comment by exit-scammed** [comment]
no problem, glad i was able to help you.
