### ISSUE TITLE
Some bug in release/beta version.

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#172]
I'll name a few bugs here, which I found. The first of them I think is even a major bug. But overall great work!

- [ ] When I hold down the right or left mouse button, my mouse sensitivity gets much faster. This is also when I do .panic all.
![image](https://user-images.githubusercontent.com/31276706/179086059-536547fc-58d3-4d58-a924-609aa6c57598.png)
Video:
https://tinyurl.com/2ea7gaen

- [ ] When I open a module, and hover on a slider sometimes a value in the setting changes randomly (+- 1 or +-0.01). It seems like #133 is causing this.
(The error is not my mouse pad. I disabled it and it still happens.)
 At the End: https://tinyurl.com/26muwk97 (Mousepad is disabled and I dont use the Mouseweel)

- [x] too much enchanted skin: [...]

- [x] Fastbow: Packets dont work at the 2th+ shot. (Always packet = 20)
(If delay > ~50ms)

- [ ] #122 (Task 5):
"Text of the modules in the middle" is missing

- [x] Hud setting: lb command border. (no direct bugfix, but needs getting used to)
![image](https://user-images.githubusercontent.com/31276706/178104636-bcf5dcc4-5988-4720-9c0e-69bbd48fe967.png)

- [x]  modul missings/bugs
Killaura: FakeSharp always on. (Only with a Sword in Hand)
Killaura: Circle not working.
AutoArmor module is missing.
.remoteview, .enchant, .give, .rename, .hurt, .holostand and shortcut command is missing

- [x] Altmanager Clip Texture
![image](https://user-images.githubusercontent.com/31276706/179089640-0f501047-9fea-4306-94bd-c9d1f791f493.png)

- [ ] Patcher: No thirdperson crosshair (fixed since 1.9+)

- [ ] ClickGUI Scale:
-bugged when I change the value at the beginning with the mouse wheel (suddenly everything large)
-It is better if the Clickgui scale starts at 0.40 instead of 0.70 (I use 0.45)
HUD Scale:
-If I change the Mc Gui scale, the HUD does not change and is then too large/small

**Comment by Tcm9** [comment]
Another bug:
too much enchanted skin:
Lb+:
![image](https://user-images.githubusercontent.com/31276706/178075064-54c42f30-fdfc-4f14-bba3-6349cc86377c.png)
Normal LB/Minecraft:
![image](https://user-images.githubusercontent.com/31276706/178075779-af963b3a-1a51-47a7-bff7-86b13ee0c625.png)

**Comment by Tcm9** [comment]
Fastbow: Packets dont work at the 2th+ shot. (Always packet = 20)
(If delay > ~50ms)

**Comment by Tcm9** [comment]
When I open a module, sometimes a value in the setting changes randomly. It seems like #133 is causing this.

**Comment by Tcm9** [comment]
#122 (Task 5):
"Text of the modules in the middle" is missing

and (Task 2):
is missing completely. (no hud setting)
(It may be that this is intentional, but I just want to point it out).

**Comment by Tcm9** [comment]
Hud setting: lb command border. (no direct bugfix, but needs getting used to)
![image](https://user-images.githubusercontent.com/31276706/178104636-bcf5dcc4-5988-4720-9c0e-69bbd48fe967.png)

**Comment by Tcm9** [comment]
cape bends into the armor when hitting.
![image](https://user-images.githubusercontent.com/31276706/178104997-b1d8a3ce-21f9-46cc-870e-18749b27c0ce.png)

**Comment by Tcm9** [comment]
Edit icon to large if Guiscale= Automatic
![image](https://user-images.githubusercontent.com/31276706/178105166-35e43053-ea20-4067-8601-6facc3c0dcbf.png)
(when a module is pressed, the icon underneath it is also pressed.)

**Comment by exit-scammed** [comment]
cape bends into the armor when hitting:
- do you have that issue with vanilla capes?

hotbar rise option:
- this is intentional, i've removed it to reduce a huge number of opengl matrix calls, mostly for performance.

**Comment by Tcm9** [comment]
ok thanks for the feedback.

1. that's what I noticed here for the first time anyway. If it's like vanilla, then I just noticed it now. Is then but also no error.

2,3,4 k, good to know.

**Comment by exit-scammed** [comment]
fastbow:
- should i modify the usage of delay value to delay packets instead of delay item c07?

**Comment by Tcm9** [comment]
could work. If then also not so many packages are spammed, then it can also bypass better.

**Comment by Tcm9** [comment]
Currently you can not press the button at all
![image](https://user-images.githubusercontent.com/31276706/178112356-5f5a45d6-a232-49fa-ba25-17f5cbe870fe.png)

**Comment by Tcm9** [comment]
What does debug actually do that so many modules have? e.g Killaura, Autopot...

**Comment by exit-scammed** [comment]
sometimes i need to test module's response to different situations, so the debug value is there to make it easier to find bugs.

**Comment by exit-scammed** [comment]
mouse sens issue: i cannot replicate that on my side though however. do you have that issue on normal lb and vanilla

**Comment by Tcm9** [comment]
I first noticed this problem in lb+. It is also only with the clickgui so and also only when changing the value via mouseweel (it does it without that I move the mouse wheel and also only at the beginning, when I hove on it. And that also only once. From then on I have to open another module and hover on a bar for this to happen again), which normally liquidbounce does not have.

**Comment by Tcm9** [comment]
You can fix the problem by using a buffer that you have to turn the mouse wheel 1-2 times before the value changes at all. This would also solve an unintentional arrival with a touchpad.

**Comment by exit-scammed** [comment]
KillAura: FakeSharp enabled by default. Added FakeSharp-SwordOnly.
KillAura: Circle not working: the circle alpha is 0 by default, so you will need to change it. Has been fixed.
AutoArmor module: has been merged with InvManager as a toggleable value.
