### ISSUE TITLE
.connect and .uuid command

### ISSUE THREAD

**Issue by Tcm9** [WYSI-Foundation/LiquidBouncePlus#173]
You can join one server to another. If you change your UUID with a bungee hack, then you can login to servers as an admin.
The CCBLUEX admin Marco did this on a German Youtuber project (Suro).
Normally a private video of the progress: https://streamable.com/u7vms

**Comment by exit-scammed** [comment]
i highly doubt that this is a server-sided plugin. however i can try to overwrite player's uniqueid from client side only and use vanilla's guiconnecting.

**Comment by exit-scammed** [comment]
finished.
