### ISSUE TITLE
suggestiooons

### ISSUE THREAD

**Issue by RangelMK** [WYSI-Foundation/LiquidBouncePlus#18]
• IP changer in-game if possible (Special) change ip option lol, where it just spoofs your ip so you can bypass max registrations per ip 

•Better Nametags and vanilla NameTag mode (So u can just easily see people's nametag's when they sneaking) mode astolfo/novoline etc..
•Cosmetics (Wings, hat's, bandanas, shield and other)
•scrollable ClickGUI (This will be more convenient than resizing even in smaller sizes)
•Seach modules in ClickGUI
•Fancy notifications
•MurderMustery Murderer finder (module)
•Remove "Press E to open inventory" notification
•Buttons in inventory and chest GUI: "Disable AutoArmor, Disable InventoryCleaner"
•add trajecties (module) 
• clickgui astolfo or vape or skeet pls astolfo
• penis esp (esp update)

**Comment by exit-scammed** [comment]
Trajectories... It's the same as Projectiles bruh
will do the others soon, but seems that I don't have time on weekdays anymore so the progress may be slow.
