### ISSUE TITLE
Can't work with some mods

### ISSUE THREAD

**Issue by Vortex-CXchenxu** [WYSI-Foundation/LiquidBouncePlus#182]
i use the hyt-party mod
the mod （hyt-party mod）can't work
but another liquidbounce can

**Comment by exit-scammed** [comment]
can you send me the mod? i cannot find it on google and it seems to be chinese

**Comment by Vortex-CXchenxu** [comment]
How can I contact you

**Comment by Vortex-CXchenxu** [comment]
[space.zip](https://github.com/WYSI-Foundation/LiquidBouncePlus/files/9175010/space.zip)
This is my decompiled source code

**Comment by exit-scammed** [comment]
i don't think the mod has anything to do with the liquidbounce+ base, you can try turning off all antiforge values and try using it again

**Comment by Vortex-CXchenxu** [comment]
JFrame cannot be created normally

**Comment by Ali00035v2** [comment]
> can you send me the mod? i cannot find it on google and it seems to be chinese

HYT stands for Huayuting which is a Chinese server.

**Comment by exit-scammed** [comment]
i already know that, but looking in the weird source code above it seems to use forge's proxy packet that may have conflict with antiforge, otherwise liquidbounce+ doesn't modify jframe's bytecode during runtime at all.
