### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by evghenii12** [WYSI-Foundation/LiquidBouncePlus#27]
/run/media/xx/256GB/LiquidBouncePlus/1.8.9-Forge/build/sources/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/gui/MixinGuiNewChat.java:327: error: reached end of file while parsing
}
 ^

**Comment by exit-scammed** [comment]
... I cant currently merge the pull request from the backup branch so things might not go as you expected, please use git cmd to clone the repo and do what `README.md` says.
