### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by evghenii12** [WYSI-Foundation/LiquidBouncePlus#29]
https://streamable.com/zs2wdd

**Comment by exit-scammed** [comment]
do you have the issue when you turn off cheststealer?

**Comment by evghenii12** [comment]
> do you have the issue when you turn off cheststealer?

Yes, but when i turn off hud i dont have this issue

**Comment by evghenii12** [comment]
Im fix this issue im turn on ChatRect ChatCombine ChatAnimation in hud settings
