### ISSUE TITLE
LiquidBouncePlus dont running in idea

### ISSUE THREAD

**Issue by evghenii12** [WYSI-Foundation/LiquidBouncePlus#30]
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class net.ccbluex.liquidbounce.features.module.modules.render.ItemPhysics, unresolved supertypes: Module
    class net.ccbluex.liquidbounce.features.module.modules.misc.SpinBot, unresolved supertypes: Module

**Comment by exit-scammed** [comment]
that's weird but can you capture your idea window and stacktrace? maybe cloning the repo into another folder may help you.
