### ISSUE TITLE
Crashing after starting

### ISSUE THREAD

**Issue by mini-programmer** [WYSI-Foundation/LiquidBouncePlus#38]
When I launch the client, after some time it shows the smaller window with LiquidbouncePlus and the icon but goes black and crashes
![Screenshot_23](https://user-images.githubusercontent.com/69440217/147278030-32b60fa4-bfee-46f1-91fa-be058fabac02.png)
I use Forge 1.8.9 and Optifine

**Comment by exit-scammed** [comment]
can you send me the latest crash report with liquidbounce+?
usually it will be in .minecraft/crash-reports

**Comment by mini-programmer** [comment]
[crash-2021-12-23_15.13.57-client.txt](https://github.com/WYSI-Foundation/LiquidBouncePlus/files/7777343/crash-2021-12-23_15.13.57-client.txt)
Here

**Comment by exit-scammed** [comment]
oh... can agree that sometimes a lb+'s build may not have Mixins' refmap generated so that's kinda normal
what version are you using? the release one or your own build?

**Comment by mini-programmer** [comment]
The release one

**Comment by exit-scammed** [comment]
can you upgrade your forge version to the latest one on forge website and notice if the error still occurs?
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.8.9.html

**Comment by mini-programmer** [comment]
it worked now but where is the Parkour module..

**Comment by exit-scammed** [comment]
> it worked now but where is the Parkour module..
i removed it long ago, but if you really need it then i can add it back asap

**Comment by mini-programmer** [comment]
You don't need to add it back asap xD
But it still would be good
