### ISSUE TITLE
[Suggestion] Add viewmodel

### ISSUE THREAD

**Issue by evghenii12** [WYSI-Foundation/LiquidBouncePlus#39]
https://www.youtube.com/watch?v=SDfQS3gTKxY

**Comment by exit-scammed** [comment]
okay but might take some time since the module is coded using forge api

**Comment by evghenii12** [comment]
Try this maybe work
https://pastebin.com/v7WXQPKR

**Comment by exit-scammed** [comment]
i think i just realized that this has been suggested before but i forgot it...
gonna add very soon

**Comment by evghenii12** [comment]
Ok thx
