### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by opZywl** [WYSI-Foundation/LiquidBouncePlus#4]
Command .focus (Nick)  (killaura/infinite aura) will focus only on this entity
Command .tp [Player Name or Position]

**Comment by exit-scammed** [comment]
will be added

**Comment by exit-scammed** [comment]
and i really hope that you don't blatantly copy and paste our code into your fdp client without any credits again, I'm too bored and my discord (server) is filled up with questions asking me why recent fdp commits are code from this repo.

**Comment by opZywl** [comment]
sorry I didn't know I was upset! Some things here I actually did for fdpclient like a blackstyle clickgui and some modules, I had seen a fork of your fdpclient and that's how I saw everything else, but I promise I'll leave credits for you every time I do something, I'm a fdp developer too, if you can pass me, disagree with your customer

**Comment by haxvzje** [comment]
anyway LB+ is a separate client

**Comment by exit-scammed** [comment]
As long as you and me credit each other when using code from both repo (this and UnlegitMC/FDPClient), I will agree with you.

**Comment by exit-scammed** [comment]
by the way I'm done with your suggestion, if you don't have anything to say then I will close this by the end of the day (GMT+7 time).

**Comment by opZywl** [comment]
i apologize for everything, i will start leaving full credits to you i am sorry for the things i have already sent!!!

**Comment by opZywl** [comment]
Does your customer have discord or any community?

**Comment by exit-scammed** [comment]
> i apologize for everything, i will start leaving full credits to you i am sorry for the things i have already sent!!!

ikr, and also tbh I don't really have a discord server, it's just a small discord group containing my friends (including a developer above - haxvzje)

**Comment by exit-scammed** [comment]
seems that you don't care about what I said anymore...
