### ISSUE TITLE
Speeds in "Other" type are very laggy

### ISSUE THREAD

**Issue by gabrielvicenteYT** [WYSI-Foundation/LiquidBouncePlus#41]
im 99% sure it's because of jumpstrafe

**Comment by exit-scammed** [comment]
what do you mean by laggy? is that fps drop or else?

**Comment by gabrielvicenteYT** [comment]
Yes FPS drop.
I go from 20 - 40 fps to 5 fps

**Comment by exit-scammed** [comment]
can you send me your most current log with that issue?
maybe i can help you.
