### ISSUE TITLE
e: Supertypes of the following classes cannot be resolved

### ISSUE THREAD

**Issue by coolfoxy** [WYSI-Foundation/LiquidBouncePlus#42]
> Task :compileKotlin FAILED
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class net.ccbluex.liquidbounce.features.module.modules.render.ItemPhysics, unresolved supertypes: Module
    class net.ccbluex.liquidbounce.features.module.modules.player.Heal, unresolved supertypes: Module
    class net.ccbluex.liquidbounce.features.module.modules.misc.SpinBot, unresolved supertypes: Module

e: C:\TeaForLiquidBounce\1.8.9reborn\src\main\java\net\ccbluex\liquidbounce\features\module\ModuleManager.kt: (135, 13): Type mismatch: inferred type is Class<ItemPhysics> but Class<out Module> was expected
e: C:\TeaForLiquidBounce\1.8.9reborn\src\main\java\net\ccbluex\liquidbounce\features\module\ModuleManager.kt: (137, 13): Type mismatch: inferred type is Class<Heal> but Class<out Module> was expected
e: C:\TeaForLiquidBounce\1.8.9reborn\src\main\java\net\ccbluex\liquidbounce\features\module\ModuleManager.kt: (147, 13): Type mismatch: inferred type is Class<SpinBot> but Class<out Module> was expected

**Comment by evghenii12** [comment]
Do you try invalidate caches?

**Comment by coolfoxy** [comment]
Yes

> Do you try invalidate caches?

**Comment by exit-scammed** [comment]
it looks like you're using your own lb+ build.
btw for intellij things i cant really help as i've never run or code lb+ in intellij ever before due to insufficient memory.

maybe this can help you: https://youtrack.jetbrains.com/issue/KT-42404#focus=Comments-27-4613153.0-0

**Comment by coolfoxy** [comment]
> it looks like you're using your own lb+ build. btw for intellij things i cant really help as i've never run or code lb+ in intellij ever before due to insufficient memory.
> 
> maybe this can help you: https://youtrack.jetbrains.com/issue/KT-42404#focus=Comments-27-4613153.0-0

thanks
