### ISSUE TITLE
Big announcement. (Please read before creating issues)

### ISSUE THREAD

**Issue by exit-scammed** [WYSI-Foundation/LiquidBouncePlus#48]
Due to health issues along with studying (seriously for money), I will suspend this project for 1 month, starting from the day I post this announcement.
Thank you for your support over the past 7 months. (shoutout to the OG one)

This also means that all things related to the client (commits, work-in-progress issues/suggestions, releases) won't be updated during this period. After I return everything will continue.

Feel free to put your problem/issue with here, will try my best to help you with it (less frequently).

**Comment by Pdx666a** [comment]
ok
