### ISSUE TITLE
hello pls

### ISSUE THREAD

**Issue by RangelMK** [WYSI-Foundation/LiquidBouncePlus#5]
hello my suggestion
![C79FE2CB-EA87-4031-AC7B-A4EB04A46CA9](https://user-images.githubusercontent.com/87137969/131554532-aafde395-df60-4f97-885d-fd7015af1478.png)

targetlist 

![44A98E2A-2294-4CB2-B66F-3335F9373265](https://user-images.githubusercontent.com/87137969/131554540-d7cfbb73-a218-424a-829c-b03710a63134.jpeg)

new speedgraph

this command very good on redestone and servers rankup/factions https://www.youtube.com/watch?v=lYQxaTLybt4

**Comment by exit-scammed** [comment]
will add soon, these things look good

**Comment by RangelMK** [comment]
TYYYYYYYYY

**Comment by exit-scammed** [comment]
currently done with addall
command `.friend <addall/removeall> <regex>`

if  you don't know what regex is, it is like a sign or your group name which is visible on player's nametag.

**Comment by RangelMK** [comment]
perfectttt the best custom build

**Comment by exit-scammed** [comment]
![image](https://user-images.githubusercontent.com/85971344/132078462-a5aa2a70-797f-4004-805e-dade145d6df4.png)
TargetList

feel free to tell me if you want to change anything.

**Comment by RangelMK** [comment]
> ![image](https://user-images.githubusercontent.com/85971344/132078462-a5aa2a70-797f-4004-805e-dade145d6df4.png)
> TargetList
> 
> feel free to tell me if you want to change anything.

This is BEEEESTTTT

**Comment by exit-scammed** [comment]
thank you, and I didn't mention that you can change how the list sorts :)
