### ISSUE TITLE
Verus nofall doesn't work with void-check

### ISSUE THREAD

**Issue by suckma420** [WYSI-Foundation/LiquidBouncePlus#51]
idk the nofall is prob borked

**Comment by exit-scammed** [comment]
hm... i don't see any problem with the code but can you send me a video of you using it?

**Comment by suckma420** [comment]
ok wait me a bit lol

**Comment by suckma420** [comment]
https://streamable.com/v1248m here

**Comment by exit-scammed** [comment]
for me verus nofall still works fine, even with void check enabled. can you send me your world/test server ip? (if you don't want to make it public you can send me through my discord in readme file.)

**Comment by suckma420** [comment]
its verusallah.mine.fun

**Comment by exit-scammed** [comment]
https://streamable.com/dllah4 for me its totally working smh

**Comment by suckma420** [comment]
bruh it works now
