### ISSUE TITLE
autoarmor invopen doesn't work😡😡😡😡😡

### ISSUE THREAD

**Issue by Rikkaaaa** [WYSI-Foundation/LiquidBouncePlus#54]

**Comment by exit-scammed** [comment]
send me your current config file (values.json + modules.json) in lb+ folder, along with a video showcasing the bug and i will help you.

**Comment by Rikkaaaa** [comment]
you can try it out yourself

**Comment by Rikkaaaa** [comment]
it wears an armor even if you dont have inventoryopen, auto ban on some server with inv check

**Comment by exit-scammed** [comment]
invopen option checks if you're in your inventory or not, so if you disable it it will just silently wear armor.
anyways i will response back after i check the module.

**Comment by Rikkaaaa** [comment]
fixed it, i just turned on all the settings except the "Hotbar"

**Comment by Rikkaaaa** [comment]
anyway, Verus combat disabler when!?

**Comment by exit-scammed** [comment]
i don't think so... if you mean the latest version since i dont pretty much play on blocksmc anymore

**Comment by Rikkaaaa** [comment]
not for blocksmc, like any experimental verus combat/semi/full disabler, or a custom disabler for verus

**Comment by exit-scammed** [comment]
i will probably try coding one sometime in march if possible since i have many school stuffs to do

**Comment by Rikkaaaa** [comment]
send me your discord

**Comment by exit-scammed** [comment]
why dont#0425

**Comment by Rikkaaaa** [comment]
#425?

**Comment by exit-scammed** [comment]
\#0425
