### ISSUE TITLE
EnemyInfo element or module

### ISSUE THREAD

**Issue by RangelMK** [WYSI-Foundation/LiquidBouncePlus#6]
![66811070-17CD-45DD-8C21-AD5D71DF2DF1](https://user-images.githubusercontent.com/87137969/131596546-b79d6bc8-6842-4538-9f2c-c7504b6325bd.png)
currently only exists Vape
but it would be nice if it had that

hmmmmm module keepsprint 
module tpaura

**Comment by exit-scammed** [comment]
keepsprint - good idea, every client nowadays does have it
tpaura - seems like a hard one for us and I'm going to skid from other clients, will credit them too if possible
enemyinfo - hmm I don't really know what are you talking about, can you give me more details? I think it's basically the Target element. 

Looking forward to your reply.

**Comment by RangelMK** [comment]
hiiiii https://www.youtube.com/watch?v=sIp4cVV5psk&feature=youtu.be this enemy info

an acquaintance did but his is not so cool

**Comment by exit-scammed** [comment]
hmm okay i see, will do soon
