### ISSUE TITLE
hud modes like rise, onetap, astolfo etc

### ISSUE THREAD

**Issue by Rikkaaaa** [WYSI-Foundation/LiquidBouncePlus#65]

**Comment by exit-scammed** [comment]
you can recreate the huds using your brain, and save them into custom themes like
```
.theme save rise
.theme save onetap
.theme save astolfo
etc.
```
and when you need to switch "hud modes" you can just `.theme load <name>`
sorry but this is to keep the original hud editor. i will probably add the theme switcher panel in the future.

**Comment by Rikkaaaa** [comment]
send me your themes
