### ISSUE TITLE
Why liquidbounceplus making screenshot of my webcam?

### ISSUE THREAD

**Issue by evghenii12** [WYSI-Foundation/LiquidBouncePlus#69]
Sometimes im see in minecraft folder file with name null/wallpaper.png.

**Comment by evghenii12** [comment]
Maybe my os problem im using linux

**Comment by exit-scammed** [comment]
i literally have no idea why its screenshotting your webcam, i've been using and developing the client for over 7 months and there's no issue tho. maybe os issue

**Comment by evghenii12** [comment]
Ok
