### ISSUE TITLE
AutoArmor Update

### ISSUE THREAD

**Issue by RangelMK** [WYSI-Foundation/LiquidBouncePlus#7]
ItemFilter - Filter Good Broken Armors
For example:
There is a lot of armor on the ground with item filter, it will only get the ones that have more durability

**Comment by exit-scammed** [comment]
... I don't really know if this is possible but vanilla mechanics just picks up every possible item near player after 1-2 seconds.
Also I'm currently doing your other requests.

**Comment by RangelMK** [comment]
ok if this is not possible, skip to something else it must be really difficult

**Comment by exit-scammed** [comment]
Closed due to invalid, impossible according to vanilla mechanics.
