### ISSUE TITLE
Please add the 1.12.2 version

### ISSUE THREAD

**Issue by hunbugs** [WYSI-Foundation/LiquidBouncePlus#74]
I want to be comfortable Hacking in Minecraft on 1.12.2

**Comment by gabrielvicenteYT** [comment]
Put that 1.8 thingy while ur on server list to 1.12.2

**Comment by exit-scammed** [comment]
currently we don't want to use the crossversion of liquidbounce as it is messy and really buggy.
but to connect you can use viaversion, at the top right of your multiplayer screen (server list) you should see a slider. Slide it till you find the version 1.12.2. (just like sigma)

**Comment by hunbugs** [comment]
Is it possible to run LiquidBouncePlus with 1.12.2?

**Comment by exit-scammed** [comment]
you can't, sadly
