### ISSUE TITLE
Please release 1.12.2!

### ISSUE THREAD

**Issue by hunbugs** [WYSI-Foundation/LiquidBouncePlus#75]

**Comment by exit-scammed** [comment]
we really want to release the 1.12.2 version but that may take a huge amount of changes including injections/variables.
not kinda possible for now

**Comment by Rikkaaaa** [comment]
> we really want to release the 1.12.2 version but that may take a huge amount of changes including injections/variables.
> not kinda possible for now

dont

**Comment by hunbugs** [comment]
; ;
