### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by RangelMK** [WYSI-Foundation/LiquidBouncePlus#8]
update radar 
![image](https://user-images.githubusercontent.com/87137969/132110889-c5d5d5b8-23dd-458e-b4f6-32f2bf140328.png)
![image](https://user-images.githubusercontent.com/87137969/132110893-8e2a6438-c2c9-4ef1-8f10-d939d9e8b087.png)

new clickgui styles hmm astolfo csgo etc
novoline top
![image](https://user-images.githubusercontent.com/87137969/132110905-f680d3c6-cc33-45e5-8f99-a89dee04d796.png)
because I didn't see different clickgui

**Comment by RangelMK** [comment]
astolfo: https://github.com/P3rZ3r0/Astolfo-Like-Clickgui

**Comment by exit-scammed** [comment]
> update radar
> ![image](https://user-images.githubusercontent.com/87137969/132110889-c5d5d5b8-23dd-458e-b4f6-32f2bf140328.png)
> ![image](https://user-images.githubusercontent.com/87137969/132110893-8e2a6438-c2c9-4ef1-8f10-d939d9e8b087.png)
![2021-09-05_11 21 50](https://user-images.githubusercontent.com/85971344/132118312-c61e21a6-55e0-4a19-a06f-af8604181ef4.png)

since I'm getting busy with these school assignments so the ClickGUI might not be done, but if possible, I will make one :)
