### ISSUE TITLE
i find wdl useless 

### ISSUE THREAD

**Issue by Rikkaaaa** [WYSI-Foundation/LiquidBouncePlus#81]

**Comment by exit-scammed** [comment]
a guy requested me to add it since there's no official forge mod for it

**Comment by suckma420** [comment]
delete it by yourself

**Comment by Rikkaaaa** [comment]
it's built in to the client and i don't see any reason to have it, u can download the mod separately using liteloader anyways

**Comment by exit-scammed** [comment]
created a separate branch for removing wdl. from next release i will add the no-wdl version.
