### ISSUE TITLE
another questionable thing about betterfps 

### ISSUE THREAD

**Issue by cheesethesylveon** [WYSI-Foundation/LiquidBouncePlus#88]
![image](https://user-images.githubusercontent.com/85301596/153104124-5ad3462d-1aef-4259-865a-eda6827de7c8.png)
from https://github.com/LizzyMaybeDev/Introduction-to-modding-mc

**Comment by exit-scammed** [comment]
so just delete betterfps and gonna recode patcher soon (since it's really unstable), new clickgui will be delayed
