### ISSUE TITLE
Strafe scaffold?

### ISSUE THREAD

**Issue by huzpsb** [WYSI-Foundation/LiquidBouncePlus#93]
No matter how i configure the scaffold,https://github.com/HawkAnticheat/Hawk
will always flag it as strafe
![image](https://user-images.githubusercontent.com/41772578/153825681-4bbfab0c-9215-43f9-a002-ab2276606d1c.png)

**Comment by exit-scammed** [comment]
can you send me your current scaffold config?

**Comment by huzpsb** [comment]
default with rotation scaffold on


p.s:could u send me your config if u can bypass?


 
---Original---
From: ***@***.***&gt;
Date: 2022/2/14 20:40:42
To: ***@***.***&gt;;
Cc: "John ***@***.******@***.***&gt;;
Subject: Re: [WYSI-Foundation/LiquidBouncePlus] Strafe scaffold? (Issue #93)




 
can you send me your current scaffold config?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
