### ISSUE TITLE
Flux's source code is public, can you skid some flux source code?

### ISSUE THREAD

**Issue by xbouind** [WYSI-Foundation/LiquidBouncePlus#94]
Flux's source code is public, can you skid some flux source code?
https://github.com/Margele/Flux-Clean-Code?

**Comment by exit-scammed** [comment]
speedrun skidding flux's disabler speed fly invcleaner modulemanager any%

has no intention to skid but will take useful modules

**Comment by xbouind** [comment]
Fakelag will crash when turned off directly after it is turned on






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月25日(星期五) 晚上7:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WYSI-Foundation/LiquidBouncePlus] Flux&#39;s source code is public, can you skid some flux source code? (Issue #94)





 
speedrun skidding flux's disabler speed fly invcleaner modulemaner any%
 
无意打滑，但会采取有用的模块
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地对通知进行分类。
您收到此邮件是因为您创作了该线程。Message ID: ***@***.***&gt;

**Comment by exit-scammed** [comment]
tbh i have no idea why but fakelag also crashes and makes your fps decrease a lot in singleplayer
will try to fix

**Comment by aaazzzww1** [comment]
skid clickgui ,targethud and clickgui

**Comment by aaazzzww1** [comment]
skid flux's clickgui ,disabler ,targethud and arraylist.

**Comment by exit-scammed** [comment]
so... flux's leaked source code is NOT the latest version and i notice many things:
- their Hypixel disabler no longer works
- we literally have a better arraylist
other than that targethud will probably be added in the next update, but i still have big issues with clickgui. not gonna add flux one.

**Comment by aaazzzww1** [comment]
ok

**Comment by exit-scammed** [comment]
all github source codes/forks got bonked.

**Comment by xbouind** [comment]
e





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月12日(星期六) 中午11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WYSI-Foundation/LiquidBouncePlus] Flux&#39;s source code is public, can you skid some flux source code? (Issue #94)





 
所有 github 源代码/分叉都被搞砸了。
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地对通知进行分类。
您收到此邮件是因为您创作了该线程。Message ID: ***@***.***&gt;
