### ISSUE TITLE
Key binding

### ISSUE THREAD

**Issue by cubigiabinh** [WYSI-Foundation/LiquidBouncePlus#95]
I know that .bind [modules] [key] will bind your key to that modules
But right now i need to bind ALT to Speed modules, but there are no way to add it
I've tried everyway even enter the code of the key name, but they just not working.
Should add the KeybindManager like FDPClient, that probably will fix my problem.

**Comment by exit-scammed** [comment]
normally our bind command use enum names for key code binding, so in this case the alt key is named LMENU.
will probably do a gui recode soon so stay tuned

**Comment by exit-scammed** [comment]
also check out this for the time being, the name you need is after "KEY_" in case you want to bind modules to keys other than alphabet.

**Comment by cubigiabinh** [comment]
> normally our bind command use enum names for key code binding, so in this case the alt key is named LMENU. will probably do a gui recode soon so stay tuned

okk
it quite like minecraft control keybinding, that why i bind killaura with GRAVE that works
thanks anyway!
