### ISSUE TITLE
Modules issue and trouble finding some modules

### ISSUE THREAD

**Issue by cubigiabinh** [WYSI-Foundation/LiquidBouncePlus#96]
ESP, ESP2D, Nametags, Killaura and many more is not working...
ESP only render myself
Killaura not killing people
I can't find Speed on the ClickGU
![Screenshot_673](https://user-images.githubusercontent.com/61140598/155829825-960677f2-dc28-4220-9715-fabd0f61f22f.png)
![Screenshot_672](https://user-images.githubusercontent.com/61140598/155829830-178fd9d7-d037-466f-b736-752226667405.png)
I

**Comment by SonThanhVN** [comment]
just scroll down in movement

**Comment by cubigiabinh** [comment]
> just scroll down in movement

uk cảm ơn
actually the biggest reason i made this issue is Killaura and many thing not working

**Comment by cubigiabinh** [comment]
> try turn off antibot or reconfig your Killaura

I tried all of them

**Comment by exit-scammed** [comment]
please, at least turn on something in the targets panel, e.g. Players
