### ISSUE TITLE
is the client still updating?

### ISSUE THREAD

**Issue by OdshDays** [WYSI-Foundation/LiquidBouncePlus#99]
^^^

**Comment by exit-scammed** [comment]
yes

**Comment by OdshDays** [comment]
> yes

oh, it had not updated in a while and I like the client, do you think it will updates soon

**Comment by exit-scammed** [comment]
yep, will try my best to update before migration for hypixel bypasses

**Comment by evghenii12** [comment]
Client updating if you want beta you can try actions.

**Comment by OdshDays** [comment]
> Client updating if you want beta you can try actions.

how?

**Comment by exit-scammed** [comment]
yes.
